---
max_level: 55
pid_file: /tmp/eqemu_char_import.pid
give_platinum: 7000
give_items:
  - 32601
import_script_db:
  database: eqemu_char_import
  host: localhost
  port: 3306
  username: eqemu_importer
  password: 
eqemu_db:
  database: eqemu
  host: localhost
  port: 3306
  username: eqemu_importer
  password: 
